# Generated by Django 4.1.6 on 2023-02-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_alter_address_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='contact',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='contactos.contact'),
        ),
    ]
